---

- name: "unarchive artificat for backend"
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

name: "update apt packages."
  become: true
  apt:
    update_cache: yes
- name: "upgrade packages."
  become: true
  apt:
    upgrade: yes

- name: start app
  become: yes
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start