---

- name: "unarchive backend files"
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: Install npm
  become: yes
  shell: npm install

- name: Stop default
  become: yes
  shell: pm2 stop default

- name: Start npm
  become: yes
  shell: pm2 start npm -- start